config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'homes#index'

  get 'about', to: 'homes#about'
  get 'services', to: 'homes#services'
  get 'contacts', to: 'homes#contacts'
  get 'products', to: 'homes#products'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController

	def index
	end

	def about
	end

	def contacts
	end

	def services
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/homes/about.html.erb
    <div class="boxed_wrapper ltr">

        <!-- preloader -->
        <div class="preloader"></div>
        <!-- preloader -->

        
        <!--Page Title-->
        <section class="page-title" style="background-image: url(assets/images/background/page-title.jpg);">
            <div class="auto-container">
                <div class="content-box">
                    <div class="title-box">
                        <h1>About Us</h1>
                    </div>
                    <ul class="bread-crumb clearfix">
                        <li><a href="index.html">Home</a></li>
                        <li>About Us</li>
                    </ul>
                </div>
            </div>
        </section>
        <!--End Page Title-->


        <!-- about-section -->
        <section class="about-section sec-pad">
            <div class="auto-container">
                <div class="inner-container mr-0 clearfix">
                    <div class="row clearfix">
                        <div class="col-lg-6 col-md-6 col-sm-12 video-column">
                            <div id="video_block_1">
                                <div class="video-inner" style="background-image: url(assets/images/resource/about-1.jpg);">
                                    <a href="https://www.youtube.com/watch?v=nfP5N9Yc72A&amp;t=28s" class="lightbox-image video-btn" data-caption=""><i class="fas fa-play"></i></a>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-6 col-md-6 col-sm-12 content-column">
                            <div id="content_block_1">
                                <div class="content-box">
                                    <div class="sec-title">
                                        <span>About Us</span>
                                        <h2>We Provide Best Meat</h2>
                                    </div>
                                    <div class="text">
                                        <p></p>
                                    </div>
                                    <ul class="list clearfix">
                                        <li>100% Organic Meat</li>
                                        <li>Payment Securation</li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <!-- about-section end -->


        <!-- service-section -->
        <section class="service-section bg-color-1">
            <div class="icon-layer" style="background-image: url(assets/images/icons/bg-icon-1.png);"></div>
            <div class="auto-container">
                <div class="sec-title text-center">
                    <span>What we do</span>
                    <h2>Services for You</h2>
                </div>
                <div class="row clearfix">
                    <div class="col-lg-4 col-md-6 col-sm-12 service-block">
                        <div class="service-block-one wow fadeInUp animated animated" data-wow-delay="00ms" data-wow-duration="1500ms">
                            <div class="inner-box">
                                <div class="icon-box"><i class="flaticon-meat-4"></i></div>
                                <h3><a href="index.html">Chicken</a></h3>
                                <p>Best Chicken</p>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-4 col-md-6 col-sm-12 service-block">
                        <div class="service-block-one wow fadeInUp animated animated" data-wow-delay="300ms" data-wow-duration="1500ms">
                            <div class="inner-box">
                                <div class="icon-box"><i class="flaticon-hang"></i></div>
                                <h3><a href="index.html">Meat</a></h3>
                                <p>Best Quality Mutton </p>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-4 col-md-6 col-sm-12 service-block">
                        <div class="service-block-one wow fadeInUp animated animated" data-wow-delay="600ms" data-wow-duration="1500ms">
                            <div class="inner-box">
                                <div class="icon-box"><i class="flaticon-meat-5"></i></div>
                                <h3><a href="index.html">Prawns, Fish</a></h3>
                                <p>Best Quality Prawns & Fish</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <!-- service-section end -->


        <!-- about-style-two -->
        <section class="about-style-two">
            <div class="auto-container">
                <div class="row align-items-center clearfix">
                    <div class="col-lg-6 col-md-12 col-sm-12 content-column">
                        <div id="content_block_2">
                            <div class="content-box">
                                <div class="sec-title style-two">
                                    <span>About Us</span>
                                    <h2>About Our Firm’s</h2>
                                </div>
                                <div class="text">
                                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris</p>
                                </div>
                                <ul class="list clearfix">
                                    <li>
                                        <i class="flaticon-call-center-agent"></i>
                                        Expert Customer
                                    </li>
                                    <li>
                                        <i class="fas fa-shipping-fast"  aria-hidden="true"></i>
                                        Free Shipping
                                    </li>
                                    <li>
                                        <i class="flaticon-return-of-investment"></i>
                                        Free Return
                                    </li>
                                    <li>
                                        <i class="flaticon-winner"></i>
                                        Amazing Deals
                                    </li>
                                </ul>
                                <div class="link-box"><a href="about.html">Learn more about our benefit<i class="flaticon-right"></i></a></div>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-6 col-md-12 col-sm-12 image-column">
                        <div id="image_block_1">
                            <div class="image-box">
                                <figure class="image image-1"><img src="assets/images/resource/about-2.jpg" alt=""></figure>
                                <figure class="image image-2"><img src="assets/images/resource/about-3.jpg" alt=""></figure>
                                <figure class="image image-3"><img src="assets/images/resource/about-1.png" alt=""></figure>
                                <figure class="image image-4"><img src="assets/images/resource/about-2.png" alt=""></figure>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <!-- about-style-two end -->


        <!-- portfolio-section -->
        <section class="portfolio-section">
            <div class="auto-container">
                <div class="single-item-carousel owl-carousel owl-theme owl-dots-none">
                    <div class="portfolio-block-one">
                        <div class="inner-box">
                            <figure class="image-box"><img src="assets/images/resource/portfolio-1.jpg" alt=""></figure>
                            <div class="lower-content">
                                <div class="inner">
                                    <span>Meat</span>
                                    <h4><a href="index.html">Pork tenderloin</a></h4>
                                    <div class="link"><a href="index.html"><i class="flaticon-right"></i></a></div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="portfolio-block-one">
                        <div class="inner-box">
                            <figure class="image-box"><img src="assets/images/resource/portfolio-2.jpg" alt=""></figure>
                            <div class="lower-content">
                                <div class="inner">
                                    <span>Meat</span>
                                    <h4><a href="index.html">Pork tenderloin</a></h4>
                                    <div class="link"><a href="index.html"><i class="flaticon-right"></i></a></div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="portfolio-block-one">
                        <div class="inner-box">
                            <figure class="image-box"><img src="assets/images/resource/portfolio-3.jpg" alt=""></figure>
                            <div class="lower-content">
                                <div class="inner">
                                    <span>Meat</span>
                                    <h4><a href="index.html">Pork tenderloin</a></h4>
                                    <div class="link"><a href="index.html"><i class="flaticon-right"></i></a></div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <!-- portfolio-section end -->

app/views/homes/contacts.html.erb
<div class="xs-sidebar-group info-group info-sidebar">
    <div class="xs-overlay xs-bg-black"></div>
    <div class="xs-sidebar-widget">
        <div class="sidebar-widget-container">
            <div class="widget-heading">
                <a href="#" class="close-side-widget">X</a>
            </div>
            <div class="sidebar-textwidget">
                <div class="sidebar-info-contents">
                    <div class="content-inner">
                        <div class="logo">
                            <a href="index.html"><%= image_tag 'logo-2.png' %></a>
                        </div>
                        <div class="content-box">
                            <h4>About Us</h4>
                            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris.</p>
                            <a href="about.html" class="theme-btn">About Us<i class="fas fa-long-arrow-alt-right"></i></a>
                        </div>
                        <div class="contact-info">
                            <h4>Contact Info</h4>
                            <ul>
                                <li>Chicago 12, Melborne City, USA</li>
                                <li><a href="tel:+8801682648101">+88 01682648101</a></li>
                                <li><a href="mailto:info@example.com">info@example.com</a></li>
                            </ul>
                        </div>
                        <ul class="social-box">
                            <li class="facebook"><a href="#" class="fab fa-facebook-f"></a></li>
                            <li class="twitter"><a href="#" class="fab fa-twitter"></a></li>
                            <li class="linkedin"><a href="#" class="fab fa-linkedin-in"></a></li>
                            <li class="instagram"><a href="#" class="fab fa-instagram"></a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- END sidebar widget item -->

app/views/homes/news.html.erb
<!-- news-section -->
<section class="news-section" id="blog">
  <div class="auto-container">
    <div class="sec-title style-two centred">
      <span>Blog & News</span>
      <h2>Latest Blog Posts</h2>
    </div>
    <div class="row clearfix">
      <div class="col-lg-4 col-md-6 col-sm-12 news-block">
        <div class="news-block-one wow fadeInUp animated animated" data-wow-delay="00ms" data-wow-duration="1500m">
          <div class="inner-box">
            <figure class="image-box"><a href="blog-details.html"><%= image_tag 'news-1.jpg' %></a></figure>
            <div class="lower-content">
              <ul class="post-info clearfix">
                <li><a href="index.html">by Leonard</a>,</li>
                <li>1 week ago</li>
              </ul>
              <h4><a href="blog-details.html">Seiusmod tempor incididunt ut labore et dolore magna</a></h4>
              <p>Lorem ipsum dolor sit amet, consec tetur adipisicing elit, sed do eiusmod tempor incididunt</p>
              <div class="link"><a href="blog-details.html">READ MORE<i class="flaticon-right"></i></a></div>
            </div>
          </div>
        </div>
      </div>
      <div class="col-lg-4 col-md-6 col-sm-12 news-block">
        <div class="news-block-one wow fadeInUp animated animated" data-wow-delay="300ms" data-wow-duration="1500m">
          <div class="inner-box">
            <figure class="image-box"><a href="blog-details.html"><%= image_tag 'news-2.jpg' %></a></figure>
            <div class="lower-content">
              <ul class="post-info clearfix">
                <li><a href="index.html">by Leonard</a>,</li>
                <li>1 week ago</li>
              </ul>
              <h4><a href="blog-details.html">Fagna aliqua Ut enim ad minim veniam, quis nostrud</a></h4>
              <p>Lorem ipsum dolor sit amet, consec tetur adipisicing elit, sed do eiusmod tempor incididunt</p>
              <div class="link"><a href="blog-details.html">READ MORE<i class="flaticon-right"></i></a></div>
            </div>
          </div>
        </div>
      </div>
      <div class="col-lg-4 col-md-6 col-sm-12 news-block">
        <div class="news-block-one wow fadeInUp animated animated" data-wow-delay="600ms" data-wow-duration="1500m">
          <div class="inner-box">
            <figure class="image-box"><a href="blog-details.html"><%= image_tag 'news-3.jpg' %></a></figure>
            <div class="lower-content">
              <ul class="post-info clearfix">
                <li><a href="index.html">by Leonard</a>,</li>
                <li>1 week ago</li>
              </ul>
              <h4><a href="blog-details.html">Golor sitmet consectetur adipisi cing eiusmod tempo</a></h4>
              <p>Lorem ipsum dolor sit amet, consec tetur adipisicing elit, sed do eiusmod tempor incididunt</p>
              <div class="link"><a href="blog-details.html">READ MORE<i class="flaticon-right"></i></a></div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
<!-- news-section end -->

app/views/homes/portfolio.html.erb
<section class="portfolio-section">
  <div class="auto-container">
    <div class="single-item-carousel owl-carousel owl-theme owl-dots-none">
      <div class="portfolio-block-one">
        <div class="inner-box">
          <figure class="image-box"><%= image_tag 'portfolio-1.jpg' %></figure>
          <div class="lower-content">
            <div class="inner">
              <span>Meat</span>
              <h4><a href="index.html">Pork tenderloin</a></h4>
              <div class="link"><a href="index.html"><i class="flaticon-right"></i></a></div>
            </div>
          </div>
        </div>
      </div>
      <div class="portfolio-block-one">
        <div class="inner-box">
          <figure class="image-box"><%= image_tag 'portfolio-2.jpg' %></figure>
          <div class="lower-content">
            <div class="inner">
              <span>Meat</span>
              <h4><a href="index.html">Pork tenderloin</a></h4>
              <div class="link"><a href="index.html"><i class="flaticon-right"></i></a></div>
            </div>
          </div>
        </div>
      </div>
      <div class="portfolio-block-one">
        <div class="inner-box">
          <figure class="image-box"><%= image_tag 'portfolio-2.jpg' %></figure>
          <div class="lower-content">
            <div class="inner">
              <span>Meat</span>
              <h4><a href="index.html">Pork tenderloin</a></h4>
              <div class="link"><a href="index.html"><i class="flaticon-right"></i></a></div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/homes/products.html.erb
<!-- shop-section -->
<section class="shop-section" id="shop">
  <div class="auto-container">
    <div class="sec-title style-two text-center">
      <span>See all products</span>
      <h2>Featured Prodcuts</h2>
    </div>
    <div class="row clearfix">
      <div class="col-lg-3 col-md-6 col-sm-12 shop-block">
        <div class="shop-block-one wow fadeInUp animated animated" data-wow-delay="00ms" data-wow-duration="1500ms">
        <div class="inner-box">
          <figure class="image-box">
            <%= image_tag 'shop-1.jpg' %>
            <ul class="list clearfix">
              <li><a href="shop-1.html"><i class="flaticon-cart"></i></a></li>
              <li><a href="shop-details.html">add to cart</a></li>
            </ul>
          </figure>
          <div class="lower-content">
            <h6><a href="shop-details.html">Whole Tenderloin</a></h6>
            <ul class="rating clearfix">
              <li><i class="fas fa-star"></i></li>
              <li><i class="fas fa-star"></i></li>
              <li><i class="fas fa-star"></i></li>
              <li><i class="fas fa-star"></i></li>
              <li><i class="fas fa-star"></i></li>
            </ul>
            <span class="price">$ 400.00</span>
          </div>
        </div>
      </div>
    </div>
    <div class="col-lg-3 col-md-6 col-sm-12 shop-block">
      <div class="shop-block-one wow fadeInUp animated animated" data-wow-delay="200ms" data-wow-duration="1500ms">
        <div class="inner-box">
          <figure class="image-box">
            <%= image_tag 'shop-2.jpg' %>
            <ul class="list clearfix">
              <li><a href="shop-1.html"><i class="flaticon-cart"></i></a></li>
              <li><a href="shop-details.html">add to cart</a></li>
            </ul>
          </figure>
          <div class="lower-content">
            <h6><a href="shop-details.html">Whole Fryer</a></h6>
            <ul class="rating clearfix">
              <li><i class="fas fa-star"></i></li>
              <li><i class="fas fa-star"></i></li>
              <li><i class="fas fa-star"></i></li>
              <li><i class="fas fa-star"></i></li>
              <li><i class="fas fa-star"></i></li>
            </ul>
            <span class="price">$ 450.00</span>
          </div>
        </div>
      </div>
    </div>
    <div class="col-lg-3 col-md-6 col-sm-12 shop-block">
      <div class="shop-block-one wow fadeInUp animated animated" data-wow-delay="400ms" data-wow-duration="1500ms">
        <div class="inner-box">
          <figure class="image-box">
            <%= image_tag 'shop-3.jpg' %>
            <ul class="list clearfix">
              <li><a href="shop-1.html"><i class="flaticon-cart"></i></a></li>
              <li><a href="shop-details.html">add to cart</a></li>
            </ul>
          </figure>
          <div class="lower-content">
            <h6><a href="shop-details.html">Rib Steak</a></h6>
            <ul class="rating clearfix">
              <li><i class="fas fa-star"></i></li>
              <li><i class="fas fa-star"></i></li>
              <li><i class="fas fa-star"></i></li>
              <li><i class="fas fa-star"></i></li>
              <li><i class="fas fa-star"></i></li>
            </ul>
            <span class="price">$ 500.00</span>
          </div>
        </div>
      </div>
    </div>
    <div class="col-lg-3 col-md-6 col-sm-12 shop-block">
      <div class="shop-block-one wow fadeInUp animated animated" data-wow-delay="600ms" data-wow-duration="1500ms">
        <div class="inner-box">
          <figure class="image-box">
            <%= image_tag 'shop-4.jpg' %>                         
            <ul class="list clearfix">
              <li><a href="shop-1.html"><i class="flaticon-cart"></i></a></li>
              <li><a href="shop-details.html">add to cart</a></li>
            </ul>
          </figure>
          <div class="lower-content">
            <h6><a href="shop-details.html">Chuck Roast</a></h6>
            <ul class="rating clearfix">
              <li><i class="fas fa-star"></i></li>
              <li><i class="fas fa-star"></i></li>
              <li><i class="fas fa-star"></i></li>
              <li><i class="fas fa-star"></i></li>
              <li><i class="fas fa-star"></i></li>
            </ul>
            <span class="price">$ 380.00</span>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="more-btn centred">
    <a href="shop-1.html" class="theme-btn">Shop Now</a>
  </div>
</section>
<!-- shop-section end -->

app/views/homes/testimonal.html.erb
<!-- testimonial-section -->
<section class="testimonial-section">
  <div class="auto-container">
    <div class="sec-title style-two">
      <span>Testimonials</span>
      <h2>Why People Believe in Us!</h2>
    </div>
    <div class="two-column-carousel owl-carousel owl-theme owl-dots-none">
      <div class="testimonial-block-one">
        <div class="inner-box">
          <div class="icon-box"><i class="flaticon-quote"></i></div>
          <p>Slore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit</p>
          <div class="author-box">
            <figure class="image-box"><%= image_tag 'testimonial-1.png' %></figure>
            <h5>Richard K. Le</h5>
            <span class="designation">HD Manager</span>
          </div>
        </div>
      </div>
      <div class="testimonial-block-one">
        <div class="inner-box">
          <div class="icon-box"><i class="flaticon-quote"></i></div>
          <p>Asi enim ad minim veniam, quis nostrud exerci tation uLorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore</p>
          <div class="author-box">
            <figure class="image-box"><%= image_tag 'testimonial-2.png' %></figure>
            <h5>Donnell J. Creech</h5>
            <span class="designation">Sonographer</span>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
<!-- testimonial-section end -->

app/views/layouts/_about.html.erb
<!-- about-section -->
<section class="about-section" id="about">
  <div class="auto-container">
    <div class="inner-container clearfix">
      <div class="row clearfix">
        <div class="col-lg-6 col-md-6 col-sm-12 video-column">
          <div id="video_block_1">
            <div class="video-inner" style="background-image: url(assets/about-1.jpg);">
              <a href="https://www.youtube.com/watch?v=nfP5N9Yc72A&amp;t=28s" class="lightbox-image video-btn" data-caption=""><i class="fas fa-play"></i></a>
            </div>
          </div>
        </div>
        <div class="col-lg-6 col-md-6 col-sm-12 content-column">
          <div id="content_block_1">
            <div class="content-box">
              <div class="sec-title">
                <span>About Us</span>
                <h2>We Provide Best Meat</h2>
              </div>
              <div class="text">
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt</p>
              </div>
              <ul class="list clearfix">
                <li>100% Organic Meat</li>
                <li>Payment Securation</li>
              </ul>
              <div class="btn-box">
                <%= link_to 'View More <i class="fas fa-long-arrow-alt-right"></i>'.html_safe, about_path, class: 'theme-btn' %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
<!-- about-section end -->

app/views/layouts/_footer.html.erb
<!-- main-footer -->
<footer class="main-footer">
  <div class="auto-container">
    <div class="footer-top">
      <div class="widget-section">
        <div class="row clearfix">
          <div class="col-lg-4 col-md-6 col-sm-12 footer-column">
            <div class="footer-widget logo-widget">
              <figure class="footer-logo"><a href="index.html"><%= image_tag 'final-logo.jpg' %></a></figure>
              <div class="text">
                <p>The probability of someone needing your services or wantinLorem ipsum dolor sit amet, consectetur adipisicing </p>
              </div>
            </div>
          </div>
          <div class="col-lg-4 col-md-6 col-sm-12 footer-column">
            <div class="footer-widget contact-widget">
              <ul class="info clearfix">
                <li>
                  <i class="fa fa-phone" aria-hidden="true"> </i> <p style="text-align: left; "> Call Us</p>
                  <h5><a href="tel:7799747770">7799747770</a></h5>
                </li>
                <li>
                  <i class="fa fa-map-marker" aria-hidden="true"> </i> <p style="text-align: left; ">Address</p>
                  <h5>Near Hanuman Junction,Hyd Road, Vinayak Nagar, Nizamabad, 503001</h5>
                </li>
              </ul>
              <ul class="social-links clearfix"> 
                <li><a href="index.html"><i class="fab fa-facebook-f" aria-hidden="true"></i></a></li>
                <li><a href="index.html"><i class="fab fa-twitter"></i> </a></li>
                <li><a href="index.html"><i class="fab fa-google-plus-g" aria-hidden="true"></i></i></a></li>
                <li><a href="index.html"><i class="fab fa-pinterest" aria-hidden="true"></i></a></li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="footer-bottom clearfix">
      <div class="copyright pull-left"><h5>&copy;2021 CopyRight www.indurfresh.com. All rights reserved.</h5></div>
      <ul class="footer-nav pull-right clearfix">
          <li><%= link_to 'Home', root_path %></li>
          <li><%= link_to 'About', about_path %></li>
          <li><%= link_to 'Contact', contacts_path %></li>
      </ul>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<!-- main header -->
<header class="main-header">
  <div class="header-top">
    <div class="auto-container">
      <div class="top-info">
        <ul class="info-list clearfix">
          <li>
            <i class="fas fa-map-marker" aria-hidden="true"> </i>
            Near Hanuman Junction, Vinayak Nagar
          </li>
          <li>
            <i class="fa fa-envelope" aria-hidden="true"></i>
            <a href="mailto:indurfreshnzb@gmail.com">indurfreshnzb@gmail.com</a>
          </li>
          <li class="phone">
            <i class="fas fa-phone" aria-hidden="true"></i>
            <a href="tel:7799747770">7799747770</a>
          </li>
        </ul>
      </div>
    </div>
  </div>
  <div class="header-upper">
    <div class="auto-container">
      <div class="outer-box clearfix">
        <div class="logo-box">
          <figure class="logo"><a href="/"><%= image_tag 'final-logo.jpg' %></a></figure>
        </div>
        <div class="menu-area pull-right">
          <!--Mobile Navigation Toggler-->
          <div class="mobile-nav-toggler">
              <i class="icon-bar"></i>
              <i class="icon-bar"></i>
              <i class="icon-bar"></i>
          </div>
          <nav class="main-menu navbar-expand-md navbar-light">
            <div class="collapse navbar-collapse show clearfix" id="navbarSupportedContent">
              <ul class="navigation scroll-nav clearfix">
                <li><%= link_to 'Home', root_path %></li>
                <li><%= link_to 'About', about_path %></li>
                <li><%= link_to 'Services', services_path %></li>
                <li><%= link_to 'Shop', products_path %></li>             
              </ul>
            </div>
          </nav>
<!--           <ul class="menu-right-content pull-left clearfix">
            <li class="user-box"><a href="index.html"><i class="fas fa-user"></i></a></li>
            <li class="search-box-outer">
              <div class="dropdown">
                <button class="search-box-btn" type="button" id="dropdownMenu3" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><span class="fas fa-search"></span></button>
                <ul class="dropdown-menu pull-right search-panel" aria-labelledby="dropdownMenu3">
                  <li class="panel-outer">
                    <div class="form-container">
                      <form method="post" action="blog.html">
                        <div class="form-group">
                          <input type="search" name="field-name" value="" placeholder="Search...." required="">
                          <button type="submit" class="search-btn"><span class="fas fa-search"></span></button>
                        </div>
                      </form>
                    </div>
                  </li>
                </ul>
              </div>
            </li>
            <li class="cart-box"><a href="shop-1.html"><i class="fas fa-shopping-cart"></i><span>0</span></a></li>
            <li class="nav-box">
              <div class="nav-btn nav-toggler navSidebar-button clearfix">
                <i class="fas fa-list"></i>
              </div>
            </li>
          </ul> -->
        </div>
      </div>
    </div>
  </div>
  <div class="sticky-header">
    <div class="auto-container">
      <div class="outer-box clearfix">
        <figure class="logo-box pull-left"><a href="/"><%= image_tag 'final-logo.jpg' %></a></figure>
        <div class="menu-area pull-right">
          <nav class="main-menu clearfix">
            <!--Keep This Empty / Menu will come through Javascript-->
          </nav>
        </div>
      </div>
    </div>
  </div>
</header>